# Import Libraries and Dataset Loading

In [ ]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as k

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [ ]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
print("X_train shape: ", X_train.shape)
print("y_train shape: ", y_train.shape)

X_train shape:  (60000, 28, 28)
y_train shape:  (60000,)


# Data Preprocessing

In [ ]:
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)

# class vector to binary class vector
y_train = keras.utils.to_categorical(y_train, num_classes = 10)
y_test = keras.utils.to_categorical(y_test, num_classes = 10)


In [ ]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [ ]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print('X train set shape: ', X_train.shape)
print(X_train.shape[0], ' training sample')
print(X_test.shape[0], ' training sample')

X train set shape:  (60000, 28, 28, 1)
60000  training sample
10000  training sample


# Creating CNN model

In [ ]:
input_shape = (28, 28, 1)

model = Sequential()
model.add(Conv2D(32, kernel_size=(3,3), activation='relu', input_shape=input_shape))
model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPooling2D(pool_size = (2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

In [ ]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer = 'adam', metrics = ['accuracy'])

# Model Training

In [ ]:
batch_size = 128
num_classes = 10
epochs = 50

model.fit(X_train, y_train, batch_size= batch_size, epochs= epochs, verbose= 1,
          validation_data=(X_test, y_test))

Epoch 1/50
469/469 [==============================] - 17s 11ms/step - loss: 0.1964 - accuracy: 0.9398 - val_loss: 0.0431 - val_accuracy: 0.9858
Epoch 2/50
469/469 [==============================] - 5s 10ms/step - loss: 0.0666 - accuracy: 0.9802 - val_loss: 0.0327 - val_accuracy: 0.9889
Epoch 3/50
469/469 [==============================] - 5s 10ms/step - loss: 0.0497 - accuracy: 0.9844 - val_loss: 0.0310 - val_accuracy: 0.9891
Epoch 4/50
469/469 [==============================] - 5s 11ms/step - loss: 0.0388 - accuracy: 0.9879 - val_loss: 0.0284 - val_accuracy: 0.9908
Epoch 5/50
469/469 [==============================] - 5s 11ms/step - loss: 0.0334 - accuracy: 0.9894 - val_loss: 0.0309 - val_accuracy: 0.9904
Epoch 6/50
469/469 [==============================] - 5s 10ms/step - loss: 0.0279 - accuracy: 0.9913 - val_loss: 0.0279 - val_accuracy: 0.9921
Epoch 7/50
469/469 [==============================] - 5s 10ms/step - loss: 0.0229 - accuracy: 0.9925 - val_loss: 0.0267 - val_accuracy: 0.992

# Save Model

In [ ]:
model.save('HW_Digit_Recognizer.h5')
print("Model has been saved")

Model has been saved


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


# Model Evaluation

In [ ]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test Score: ", score[0])
print("Test Accuracy: ", score[1])

Test Score:  0.03855883702635765
Test Accuracy:  0.9937000274658203
